### ISSUE TITLE
Bug: GoDaddy Error Malformed Secret

### ISSUE THREAD

**Issue by ionbasa** [qdm12/ddns-updater#169]
**TLDR**: GoDaddy does not work. Error shows malformed secret
1. Is this urgent: Yes
2. DNS provider(s) you use: GoDaddy
3. Program version:  Running version latest built on 2021-02-11T13:41:05Z (commit caa4840)
4. What are you using to run the container: docker-compose
5. Extra information

Logs:

```
ddns-updater    | =========================================
ddns-updater    | =========================================
ddns-updater    | ========= DDNS Universal Updater ========
ddns-updater    | =========================================
ddns-updater    | === Made with ❤️  by github.com/qdm12 ====
ddns-updater    | =========================================
ddns-updater    |
ddns-updater    | Running version latest built on 2021-02-11T13:41:05Z (commit caa4840)
ddns-updater    |
ddns-updater    |
ddns-updater    | 🔧  Need help? https://github.com/qdm12/ddns-updater/issues/new
ddns-updater    | 💻  Email? quentin.mcgaw@gmail.com
ddns-updater    | ☕  Slack? Join from the Slack button on Github
ddns-updater    | 💸  Help me? https://github.com/sponsors/qdm12
ddns-updater    | 2021-02-12T04:43:46.066Z      ERROR   malformed secret
ddns-updater exited with code 1

```

Configuration file (**remove your credentials!**):

```
{
  "settings": [
    {
      "provider": "godaddy",
      "domain": "ABCD.org",
      "host": "@",
      "key": "key",
      "secret": "secret",
      "ip_version": "ipv4"
    }
  ]
}


```

Host OS: Ubuntu 18.04 LTS

Note: I know my API key works. There is an example CURL command here: https://developer.godaddy.com/getstarted

```
curl -X GET -H"Authorization: sso-key [API_KEY]:[API_SECRET]" "https://api.godaddy.com/v1/domains/available?domain=example.guru"
```

**Comment by ionbasa** [comment]
My Secret key is actually **21** characters. Not sure if that is because it is an older key.

I assume the issue is caused by the following line:
https://github.com/qdm12/ddns-updater/blob/caa4840a6107b58b8d2e86a70771718743726623/internal/regex/regex.go#L33 #

**Comment by qdm12** [comment]
Indeed, thanks for digging in the code! Should now be fixed in `:latest` once it's built. Feel free to comment if it does/doesn't work 👍

**Comment by ionbasa** [comment]
@qdm12 


I pulled the latest build this morning to try out and I am still having the error. See below:

Version:  latest built on 2021-02-12T14:39:59Z (commit c985595)
```
ddns-updater    | =========================================
ddns-updater    | =========================================
ddns-updater    | ========= DDNS Universal Updater ========
ddns-updater    | =========================================
ddns-updater    | === Made with ❤️  by github.com/qdm12 ====
ddns-updater    | =========================================
ddns-updater    |
ddns-updater    | Running version latest built on 2021-02-12T14:39:59Z (commit c985595)
ddns-updater    |
ddns-updater    |
ddns-updater    | 🔧  Need help? https://github.com/qdm12/ddns-updater/issues/new
ddns-updater    | 💻  Email? quentin.mcgaw@gmail.com
ddns-updater    | ☕  Slack? Join from the Slack button on Github
ddns-updater    | 💸  Help me? https://github.com/sponsors/qdm12
ddns-updater    | 2021-02-13T20:13:54.811Z      ERROR   malformed secret
```

It is still showing a malformed secret error.

**Comment by qdm12** [comment]
I removed the check entirely for now (except check it's not empty) in 2e5b3c79240888d0c3189223fe78d1b3ddab68a5

Please wait for the build to complete (check Github Actions) and then try by pulling it again 😉

**Comment by ionbasa** [comment]
It works!

```
ddns-updater    | =========================================
ddns-updater    | =========================================
ddns-updater    | ========= DDNS Universal Updater ========
ddns-updater    | =========================================
ddns-updater    | === Made with ❤️  by github.com/qdm12 ====
ddns-updater    | =========================================
ddns-updater    |
ddns-updater    | Running version latest built on 2021-02-13T20:30:07Z (commit 2e5b3c7)
ddns-updater    |
ddns-updater    |
ddns-updater    | 🔧  Need help? https://github.com/qdm12/ddns-updater/issues/new
ddns-updater    | 💻  Email? quentin.mcgaw@gmail.com
ddns-updater    | ☕  Slack? Join from the Slack button on Github
ddns-updater    | 💸  Help me? https://github.com/sponsors/qdm12
ddns-updater    | 2021-02-13T22:12:05.311Z      INFO    Found single setting to update record
ddns-updater    | 2021-02-13T22:12:05.509Z      INFO    Reading history from database: domain ABCD.org host XYZ
ddns-updater    | 2021-02-13T22:12:05.510Z      INFO    healthcheck server: listening on 127.0.0.1:9999
ddns-updater    | 2021-02-13T22:12:05.510Z      INFO    http server: listening on 0.0.0.0:8000
ddns-updater    | 2021-02-13T22:12:05.510Z      INFO    backup: disabled
```

I sanitized the domain and host in the log output. Thank you so much. Let me know if you need an example of my 21 character secret key to fix the main cause.
